apiVersion: v1
kind: Service
metadata:
  name: code-swarm
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: code-swarm
